-- Asignaturas
INSERT INTO asignaturas (nombre) VALUES
('Apoyo Música'),
('Música'),
('APOYO'),
('Educación Física'),
('APOYO SOCIOLINGUISTICO'),
('APOYO FRANCES'),
('FRANCES'),
('CoTutoría'),
('Tutoría'),
('EDUCACION PLATICA Y VISUAL'),
('APOYO EPV'),
('Ciencias Sociales'),
('APOYO PT'),
('ORATORIA Y DEBATE'),
('COMPUTACION Y ROBOTICA'),
('Religión'),
('ATENCION EDUCATIVA'),
('Religión EVANGELICA'),
('APOYO INGLES'),
('Inglés'),
('Lengua'),
('Matemáticas'),
('Biología y Geología'),
('APOYO Lengua'),
('Francés'),
('Vida Saludable'),
('APOYD'),
('Física y Química'),
('APOYO CN'),
('Geografía e Historia'),
('APOYO CSO'),
('INGLES'),
('Lengua Castellana'),
('Apoyo Tecnología'),
('Tecnología'),
('BIOLOGIA'),
('CULTURA DEL FLAMENCO'),
('TALLER LABORATORIO'),
('EPV'),
('ARTES ESCENICAS Y DANZA'),
('CULTURA CIENTIFICA'),
('ILUSTRACION Y ACUARELA'),
('Tecnología y digitalizacion'),
('AMBITO CIENTIFICO-TECNICO'),
('AMBITO SOCIOLINGUISTICO'),
('Tutoría orientación');