# Para usar el modo production con Resend define al menos:
# RESEND_API_KEY
# RESEND_FROM
# RESEND_REPLY_TO opcional
app.password-recovery.mode=testing
resend.api.key=re_WSWMce9M_EbjLjjdS9XFpbs9QxwtVFjxC
resend.from=no-reply@iespoligonosur.org
resend.reply-to=${RESEND_REPLY_TO:}
